# Generated by Django 5.1.3 on 2024-12-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('PersonID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
            ],
            options={
                'db_table': 'People',
            },
        ),
    ]
