# Generated by Django 5.1.3 on 2024-12-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={'managed': False},
        ),
    ]
