# Generated by Django 5.1.3 on 2024-12-19 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_people_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
